# Generated by Django 3.2.4 on 2021-06-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=125)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.room')),
            ],
            options={
                'unique_together': {('date', 'room_id')},
            },
        ),
    ]
