# Generated by Django 3.2.4 on 2021-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='projector',
            field=models.BooleanField(default=True),
        ),
    ]
